name: paapag_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5

  # BASE
  intl: 0.17.0
  html: 0.15.1
  shared_preferences: 2.1.1
  google_fonts: 3.0.1

  # CONNECTIVITY
  http: 0.13.6
  connectivity_plus: 3.0.2

  # STATE MANAGEMENT
  mobx: 2.2.0
  flutter_mobx: 2.0.6+5

  # TOAST
  fluttertoast: 8.1.1

  # IMAGE
  cached_network_image: 3.2.2
  image_picker: 0.8.6

  # UI
  lottie: 2.0.0
  fl_chart: 0.55.2
  charts_flutter: 0.12.0
  syncfusion_flutter_charts: 20.3.58
  flutter_switch: 0.3.2

  # COUNTRY
  country_code_picker_x: 2.0.5

  # PACKAGE INFO
  #package_info_plus: 3.0.2

  # LUNCH URL
  url_launcher: 6.1.7

  # TIMELINE
  timeline_tile: 2.0.0

  # DATE TIME PICKER
  date_time_picker: 2.1.0

  elegant_notification: 1.6.4

  # CURRENCY PICKER
  #currency_picker: 2.0.15

  # READ MORE LESS
  readmore: 2.2.0

  # GOOGLE MAP
  maps_launcher: 2.0.1

  # DOWNLOAD INVOICE PDF
  pdf: 3.8.3
  printing: 5.9.3

  universal_html: 2.0.8

  #COMMON
  flutter_vector_icons: 2.0.0

  #UI
  responsive_grid_list: 1.3.0
  shimmer: 2.0.0

  #OTHER
  file_picker: 4.5.1

  url_strategy: 0.2.0

  # DOWNLOAD INVOICE PDF
  path_provider: 2.0.11

  flutter_localizations:
    sdk: flutter
  firebase_core: 1.24.0
  firebase_messaging: 13.1.0
  firebase_auth: 3.11.2
  cloud_firestore: 3.5.1
  firebase_crashlytics: 2.9.0
  firebase_storage: 10.3.11
  firebase_database: 9.1.7
  paginate_firestore: 1.0.3+1
  currency_picker: 2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.3.2
  mobx_codegen: 2.3.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/flag/
    - assets/partener/

#dependency_overrides:
#  firebase_core_platform_interface: 4.5.1
